# Generated by Django 5.1.2 on 2024-10-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0003_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя сотрудников')),
                ('post', models.CharField(max_length=150, verbose_name='Должность')),
                ('ranking', models.IntegerField(max_length=20, verbose_name='Ранг')),
                ('checklist', models.IntegerField(max_length=150, verbose_name='Кол-во задании')),
                ('experiences', models.IntegerField(max_length=100, verbose_name='Опыт')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
