# Generated by Django 5.1.2 on 2024-10-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0004_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная задача'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Имя сотрудника'),
        ),
    ]
