# Generated by Django 5.1.2 on 2024-11-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0005_tasks_is_active_alter_employees_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='image',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='title',
        ),
        migrations.AlterField(
            model_name='employees',
            name='checklist',
            field=models.IntegerField(verbose_name='Кол-во задании'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='experiences',
            field=models.IntegerField(verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='ranking',
            field=models.IntegerField(verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активная задача'),
        ),
    ]
